version: '3.8'

services:
  app:
    build: .
    ports:
      - "443:443"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: loyaltydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
